name: fire_chat
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.4
  image_picker: ^1.1.2
  provider: ^6.1.2
  http: ^1.3.0
  flutter_local_notifications: ^18.0.1
  file_picker: ^9.0.2
  flutter_sound: ^9.25.4
  permission_handler: ^11.4.0

  just_audio: ^0.9.46
  audio_session: ^0.1.25
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  easy_image_viewer: ^1.5.1
  flutter_link_previewer: ^3.2.2
  flutter_chat_types: ^3.6.2
  string_contains: ^2.4.0
  chaty: 1.0.4
  firebase_app_check: ^0.3.2+5

  printing:
    ^5.12.0
  flutter_native_html_to_pdf: ^1.0.1
  share_plus: ^11.0.0
    # git:
    #   url: https://github.com/mindsterapps/chaty.git
    #   ref: 1.1.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
