name: fire_chat
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.4
  image_picker: ^1.1.2
  provider: ^6.1.2
  http: ^1.3.0
  flutter_local_notifications: ^18.0.1
  file_picker: ^9.0.2
  flutter_sound: ^9.25.4
  permission_handler: ^11.4.0
  # chaty:
  #   git:
  #     url: https://github.com/aswintbbc/chaty.git
  #     ref: 1.0.18
  voice_message_package: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
