// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABkFPB-bRAnl_M57RNoJTvi9Z2HZeWTNo',
    appId: '1:806352115565:android:beb6b3dfd7b709a94a2c64',
    messagingSenderId: '806352115565',
    projectId: 'testing-6b899',
    databaseURL:
        'https://fitreat-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testing-6b899.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLGYn7SQFKg1FoV-LEBTGvoPzrhqXc2HY',
    appId: '1:647451189575:ios:78beb0b1a10b98b9832c62',
    messagingSenderId: '806352115565',
    projectId: 'testing-6b899',
    databaseURL:
        'https://fitreat-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testing-6b899.firebasestorage.app',
    iosBundleId: 'com.example.fire_chat',
  );
}
